// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// IOperatorHandler is an autogenerated mock type for the IOperatorHandler type
type IOperatorHandler struct {
	mock.Mock
}

// GetOperator provides a mock function with given fields: c
func (_m *IOperatorHandler) GetOperator(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PutOperator provides a mock function with given fields: c
func (_m *IOperatorHandler) PutOperator(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIOperatorHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewIOperatorHandler creates a new instance of IOperatorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIOperatorHandler(t mockConstructorTestingTNewIOperatorHandler) *IOperatorHandler {
	mock := &IOperatorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
