// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// IResetHandler is an autogenerated mock type for the IResetHandler type
type IResetHandler struct {
	mock.Mock
}

// Reset provides a mock function with given fields: c
func (_m *IResetHandler) Reset(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIResetHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewIResetHandler creates a new instance of IResetHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIResetHandler(t mockConstructorTestingTNewIResetHandler) *IResetHandler {
	mock := &IResetHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
