// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IResetUsecase is an autogenerated mock type for the IResetUsecase type
type IResetUsecase struct {
	mock.Mock
}

// Reset provides a mock function with given fields: apikey
func (_m *IResetUsecase) Reset(apikey string) error {
	ret := _m.Called(apikey)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(apikey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIResetUsecase creates a new instance of IResetUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIResetUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IResetUsecase {
	mock := &IResetUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
